server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: service-gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/service-auth/**
          filters:
            - StripPrefix=1
        - id: service-api
          uri: lb://service-api
          predicates:
            - Path=/service-api/**
          filters:
            - StripPrefix=1
        - id: service-admin
          uri: lb://service-admin
          predicates:
            - Path=/service-admin/**
          filters:
            - StripPrefix=1
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/service-msm/**
          filters:
            - StripPrefix=1
        - id: service-ledger
          uri: lb://service-ledger
          predicates:
            - Path=/service-ledger/**
          filters:
            - StripPrefix=1
        - id: service-capital
          uri: lb://service-capital
          predicates:
            - Path=/service-capital/**
          filters:
            - StripPrefix=1
        - id: service-risk
          uri: lb://service-risk
          predicates:
            - Path=/service-risk/**
          filters:
            - StripPrefix=1
        - id: service-reimbursement
          uri: lb://service-reimbursement
          predicates:
            - Path=/service-reimbursement/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: http://localhost:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/service-auth/oauth/token"
      - "/service-auth/rsa/publicKey"
      - "/service-admin/admin/login"
      - "/service-admin/admin/register"
      - "/service-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
